[env:esp32-s3-devkitc-1]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = espidf

monitor_speed = 115200

board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv

build_flags =
    -DCONFIG_COL_LED=38
    -DCONFIG_ROW_LED=39
    -DCONFIG_PULSE_LED=40
    -DCONFIG_SEL_PANEL_1=4
    -DCONFIG_SEL_PANEL_2=5
    -DCONFIG_SEL_PANEL_3=6
    -DCONFIG_SEL_PANEL_4=7
    -DCONFIG_SET_UNSET=12
    -DCONFIG_COL_ADV=8
    -DCONFIG_ROW_ADV=13
    -DCONFIG_PULSE_SIG=41
    -DCONFIG_PANEL_RESET=47